env:
  contexts:
    - name: "local-web-test"
      urls:
        - "http://localhost:8080/"

  parameters:
    failOnError: false

jobs:
  - type: spider
    name: "Spider website"
    parameters:
      context: "local-web-test"
      maxDuration: 5   # increased duration

  - type: activeScan
    name: "Active Scan"
    parameters:
      context: "local-web-test"

  - type: report
    name: "Generate HTML Report"
    parameters:
      template: traditional-html
      reportDir: "./zap_results"
      reportFile: "zap_report.html"

