env:
  contexts:
    - name: "local-web-test"
      urls:
        - "http://localhost:8080/"

  parameters:
    failOnError: false
    progressToStdout: true   # helpful for GitHub Action logs

jobs:
  - type: spider
    name: "Spider website"
    parameters:
      context: "local-web-test"
      maxDuration: 5

  - type: activeScan
    name: "Active Scan"
    parameters:
      context: "local-web-test"

  - type: report
    name: "Generate HTML Report"
    parameters:
      template: traditional-html
      reportDir: "/zap/wrk/zap_results"
      reportFile: "zap_report.html"
