env:
  contexts:
    - name: "local-web-test"
      urls:
        - "http://localhost:8080/"   # match Docker container port

  parameters:
    failOnError: false

jobs:
  - type: spider
    name: "Spider website"
    parameters:
      context: "local-web-test"
      maxDuration: 1   # in minutes

  - type: activeScan
    name: "Active Scan"
    parameters:
      context: "local-web-test"

  - type: report
    name: "Generate HTML Report"
    parameters:
      template: traditional-html
      reportDir: "/home/seed/hardened-webserver-project"   # use absolute path
      reportFile: "zap_report.html"

